### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by nitesh-mishr** [MFDGaming/ubuntu-in-termux#30] opened 2019-09-11 07:18 UTC
When i type
$ ./start.sh
I get following error 

/usr/bin/env: '/bin/bash': No such file or directory
Can any one help me

**Comment by MFDGaming** [comment] 2019-09-11 10:20
Can you give me more info

**Comment by MFDGaming** [comment] 2019-09-11 10:21
@nitesh-mishr

**Comment by nitesh-mishr** [comment] 2019-09-11 13:03
i have followed the command which were given in the respirotary


> Can you give me more info

I have followed the same command given by you in Repositorie and i get the error shown in photo 

- [ ] [
![Screenshot_20190911-182408_Termux](https://user-images.githubusercontent.com/46121792/64699563-acd69a00-d4c2-11e9-8ed6-b9f9af272458.jpg)
](url)

**Comment by Awakened-Redstone** [comment] 2019-09-11 17:02
Same for me

**Comment by MFDGaming** [comment] 2019-10-03 19:41
The problem is that your device is not downloading the stuff correctly. I have to check why it does not work on your device. (In mine it works) what architecture do you have?

**Comment by MFDGaming** [comment] 2019-10-03 19:42
@pavankmr853

**Comment by MFDGaming** [comment] 2019-10-03 19:42
@nitesh-mishr

**Comment by MFDGaming** [comment] 2019-10-03 19:43
And sorry for not answering at the correct time. I was quite busy

**Comment by MFDGaming** [comment] 2019-10-16 19:19
This issue is here for too long. I have to close it

**Comment by MFDGaming** [comment] 2019-10-16 19:19
I

**Closed by MFDGaming** 2019-10-16 19:19 UTC

**Comment by nitesh-mishr** [comment] 2019-10-17 01:01
Can you give me solution
I phone is j 7 prime

**Comment by MFDGaming** [comment] 2019-12-04 14:01
@nitesh-mishr try it again with my new install script
